---
apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: {{ .Values.Namespace }}
  name: tgtubenotibot
  labels:
    app: tgtubenotibot
spec:
  schedule: "{{ .Values.CronSchedule }}"
  selector:
    matchLabels:
      app: tgtubenotibot
  jobTemplate:
    metadata:
      name: tgtubenotibot
      labels:
        app: tgtubenotibot
      annotations:
        checksum/configmap-tgtubenotibot: {{ include ( print $.Template.BasePath "/" "configmap-tgtubenotibot.yaml" ) . | sha256sum }}
    spec:
      containers:
      - name: tgtubenotibot
        imagePullPolicy: Always
        image: {{ .Values.ImageName }}:{{ .Values.ImageTag }}
        envFrom:
          - configMapRef:
              name: tgtubenotibot
