---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.Namespace }}
  name: tgtubenotibot
  labels:
    app: tgtubenotibot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tgtubenotibot
  template:
    metadata:
      name: tgtubenotibot
      labels:
        app: tgtubenotibot
      annotations:
        checksum/configmap-tgtubenotibot: {{ include ( print $.Template.BasePath "/" "configmap-tgtubenotibot.yaml" ) . | sha256sum }}
    spec:
      containers:
      - name: tgtubenotibot
        imagePullPolicy: Always
        image: {{ .Values.ImageName }}:{{ .Values.ImageTag }}
        envFrom:
          - configMapRef:
              name: tgtubenotibot
