---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.Namespace }}
  name: {{ .Values.Namespace }}-tgtubenotibot
  labels:
    app: {{ .Values.Namespace }}-tgtubenotibot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.Namespace }}-tgtubenotibot
  template:
    metadata:
      name: {{ .Values.Namespace }}-tgtubenotibot
      labels:
        app: {{ .Values.Namespace }}-tgtubenotibot
      annotations:
        checksum/configmap-zzdevopsbot: {{ include ( print $.Template.BasePath "/" "configmap-tgtubenotibot.yaml" ) . | sha256sum }}
    spec:
      containers:
      - name: {{ .Values.Namespace }}-tgtubenotibot
        imagePullPolicy: Always
        image: {{ .Values.ImageName }}:{{ .Values.ImageTag }}
        envFrom:
          - configMapRef:
              name: {{ .Values.Namespace }}-tgtubenotibot
